# Generated by Django 3.0.8 on 2020-07-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200713_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='Creation_time',
            new_name='creation_time',
        ),
    ]
